# Generated by Django 3.2.6 on 2021-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave_app', '0002_nfts_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfts',
            old_name='user_id',
            new_name='seller_id',
        ),
        migrations.AddField(
            model_name='nfts',
            name='buyer_id',
            field=models.CharField(default='k', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfts',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
