# Generated by Django 3.2.6 on 2021-11-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave_app', '0003_auto_20211118_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
