# Generated by Django 3.2.6 on 2021-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave_app', '0004_nfts_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='applied_for_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
