# Generated by Django 3.2.6 on 2021-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave_app', '0005_nfts_applied_for_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='wallet_address',
            field=models.CharField(default='dsadas', max_length=200),
            preserve_default=False,
        ),
    ]
